import { useState } from 'react';
import { useParams , useOutletContext} from 'react-router-dom';
import { supabase } from '../../lib/supabaseClient';
import { ShieldAlert, Play, RotateCcw, AlertTriangle, UserX, WifiOff, CalendarX, PackageX, CheckCircle } from 'lucide-react';

const SCENARIOS = [
  {
    id: 'S1',
    code: 'VEHICLE_DISINFECTION_FAILED',
    title: 'S1: Xe chưa sát trùng vào khu nội bộ',
    desc: 'Hệ thống nhận diện xe đi qua cổng nhưng không ghi nhận hoàn tất sát trùng. Xe tiếp tục di chuyển vào khu vực chuồng nuôi.',
    riskLevel: 'Critical',
    riskPoints: 30,
    icon: <AlertTriangle className="text-red-500" size={24} />,
    color: 'border-red-500'
  },
  {
    id: 'S2',
    code: 'PERSONNEL_CLEAN_ZONE_VIOLATION',
    title: 'S2: Người vào khu sạch sai quy trình',
    desc: 'Nhân viên/Khách đi vào khu sạch nhưng chưa hoàn tất quy trình tắm, thay đồ sát trùng.',
    riskLevel: 'Critical',
    riskPoints: 30,
    icon: <UserX className="text-red-500" size={24} />,
    color: 'border-red-500'
  },
  {
    id: 'S3',
    code: 'DEVICE_OFFLINE_HIGH_RISK',
    title: 'S3: Mất tín hiệu thiết bị vùng nhạy cảm',
    desc: 'Thiết bị UWB/Camera trong chuồng nái/cách ly bị offline quá thời gian cho phép.',
    riskLevel: 'High',
    riskPoints: 20,
    icon: <WifiOff className="text-orange-500" size={24} />,
    color: 'border-orange-500'
  },
  {
    id: 'S4',
    code: 'BARN_CLEANING_OVERDUE',
    title: 'S4: Chuồng quá hạn vệ sinh',
    desc: 'Chuồng heo nái đã đến kỳ vệ sinh nhưng hệ thống chưa ghi nhận cleaning log hoặc chưa đủ số lần.',
    riskLevel: 'High',
    riskPoints: 20,
    icon: <CalendarX className="text-orange-500" size={24} />,
    color: 'border-orange-500'
  },
  {
    id: 'S5',
    code: 'SUPPLY_UNAPPROVED_ENTRY',
    title: 'S5: Vật tư vào khu nuôi chưa phê duyệt',
    desc: 'Lô vật tư, dụng cụ đi vào khu sạch/chuồng nuôi khi chưa được xác nhận kiểm tra, sát trùng.',
    riskLevel: 'Critical',
    riskPoints: 25,
    icon: <PackageX className="text-red-500" size={24} />,
    color: 'border-red-500'
  }
];

export default function MoPhongRuiRo() {
  const { farmId } = useOutletContext<{ farmId: string }>();
  const [running, setRunning] = useState<string | null>(null);
  const [resetting, setResetting] = useState(false);
  const [toast, setToast] = useState<{msg: string, type: 'success'|'error'} | null>(null);

  const showToast = (msg: string, type: 'success'|'error') => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3000);
  };

  const handleRunSimulation = async (scenario: typeof SCENARIOS[0]) => {
    if (!farmId) return;
    setRunning(scenario.id);

    try {
      // 1. Tăng điểm Risk Score của Farm (nếu DB hỗ trợ, nếu lỗi thì bỏ qua)
      let newScore = 0;
      try {
        const { data: farm } = await supabase.from('farms').select('risk_score').eq('id', farmId).single();
        const currentScore = farm?.risk_score || 0;
        newScore = currentScore + scenario.riskPoints;
        if (newScore > 100) newScore = 100;
        await supabase.from('farms').update({ risk_score: newScore }).eq('id', farmId);
      } catch (e) {
        console.warn('Không thể cập nhật risk_score trên DB, có thể do thiếu cột.', e);
      }

      // 2. Tạo Alert
      let recommendedAction = '';
      if (scenario.id === 'S1') recommendedAction = 'Dừng xe — yêu cầu quay lại khu sát trùng — xác nhận lại sau sát trùng';
      else if (scenario.id === 'S2') recommendedAction = 'Yêu cầu rời khỏi khu sạch — thực hiện lại quy trình tắm/sát trùng — ghi nhận biên bản';
      else if (scenario.id === 'S3') recommendedAction = 'Kiểm tra nguồn điện thiết bị - Cử kỹ thuật viên kiểm tra phần cứng';
      else if (scenario.id === 'S4') recommendedAction = 'Phân công lại tác vụ vệ sinh - Thực hiện vệ sinh khẩn cấp';
      else if (scenario.id === 'S5') recommendedAction = 'Cô lập lô vật tư — kiểm tra — sát trùng — phê duyệt lại';

      const { error: alertError } = await supabase.from('alerts').insert({
        farm_id: farmId,
        alert_code: `SIM-${scenario.id}-${Date.now().toString().slice(-4)}`,
        alert_type: 'Mô phỏng rủi ro ATSH',
        severity: scenario.riskLevel === 'Critical' ? 'Nghiêm trọng' : 'Cao',
        message: `${scenario.desc}\n(Hành động: ${recommendedAction})`,
        status: 'Chưa xử lý'
      });

      if (alertError) {
        throw alertError;
      }

      // 3. Tự động ghi log vào các bảng Báo Cáo
      const runId = `RUN-${Date.now()}`;
      
      if (scenario.id === 'S4') {
        // Tình huống S4: Tạo log vệ sinh chuồng quá hạn
        const { error: s4Error } = await supabase.from('cleaning_tasks').insert([
          {
            farm_id: farmId,
            target_zone: 'Chuồng Nái 1',
            task_name: 'Vệ sinh định kỳ (Auto-generated by S4)',
            assigned_to: 'Nhân viên B',
            scheduled_time: new Date(Date.now() - 3600000 * 5).toISOString(), // Quá hạn 5 tiếng
            status: 'Overdue',
            scenario_run_id: runId
          },
          {
            farm_id: farmId,
            target_zone: 'Chuồng Đẻ 3',
            task_name: 'Sát trùng lối đi (Auto-generated by S4)',
            assigned_to: 'Nhân viên C',
            scheduled_time: new Date(Date.now() + 3600000 * 2).toISOString(), // Sắp tới
            status: 'Pending',
            scenario_run_id: runId
          }
        ]);
        if (s4Error) console.error('Lỗi khi tạo mock cleaning_tasks:', s4Error);
      }

      showToast(`Chạy thành công: ${scenario.title}`, 'success');

    } catch (error: any) {
      console.error('Simulation error:', error);
      showToast('Có lỗi xảy ra: ' + (error?.message || 'Không xác định'), 'error');
    } finally {
      setRunning(null);
    }
  };

  const handleReset = async () => {
    if (!farmId) return;
    setResetting(true);
    try {
      // Xoá alerts tạo ra từ mô phỏng
      await supabase.from('alerts').delete().eq('farm_id', farmId).eq('alert_type', 'Mô phỏng rủi ro ATSH');
      
      // Xoá các data báo cáo giả lập
      await supabase.from('cleaning_tasks').delete().eq('farm_id', farmId).like('task_name', '%Auto-generated%');
      
      try {
        // Reset điểm (nếu DB hỗ trợ)
        await supabase.from('farms').update({ risk_score: 0 }).eq('id', farmId);
      } catch (e) {
        console.warn('Không thể reset risk_score trên DB.', e);
      }
      
      // Clear IoT test zone
      localStorage.removeItem('iot_selected_zone');
      window.dispatchEvent(new Event('iot_zone_changed'));
      
      showToast('Đã Reset dữ liệu mô phỏng thành công!', 'success');
    } catch (error) {
      console.error(error);
      showToast('Lỗi khi reset dữ liệu!', 'error');
    } finally {
      setResetting(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center bg-white p-4 rounded-xl shadow-sm border border-gray-100">
        <div className="flex items-center text-gray-700">
          <ShieldAlert className="mr-2 text-blue-600" />
          <h2 className="text-lg font-bold">Biosecurity Risk Simulation Scenarios</h2>
        </div>
        <button 
          onClick={handleReset}
          disabled={resetting}
          className="bg-gray-100 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-200 flex items-center transition-colors"
        >
          <RotateCcw size={16} className={`mr-2 ${resetting ? 'animate-spin' : ''}`} />
          Reset Simulation Data
        </button>
      </div>

      {toast && (
        <div className={`p-4 rounded-lg shadow-md flex items-center text-white ${toast.type === 'success' ? 'bg-green-600' : 'bg-red-600'}`}>
          <CheckCircle className="mr-2" size={20} />
          {toast.msg}
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {SCENARIOS.map((sc) => (
          <div key={sc.id} className={`bg-white rounded-xl shadow-sm border-t-4 ${sc.color} p-5 flex flex-col justify-between hover:shadow-md transition-shadow`}>
            <div>
              <div className="flex justify-between items-start mb-3">
                <div className="p-2 bg-gray-50 rounded-lg">
                  {sc.icon}
                </div>
                <div className="flex flex-col items-end">
                  <span className={`px-2 py-1 rounded text-xs font-bold ${sc.riskLevel === 'Critical' ? 'bg-red-100 text-red-700' : 'bg-orange-100 text-orange-700'}`}>
                    {sc.riskLevel}
                  </span>
                  <span className="text-xs text-gray-500 font-medium mt-1">+{sc.riskPoints} Risk Score</span>
                </div>
              </div>
              <h3 className="font-bold text-gray-800 text-base mb-2">{sc.title}</h3>
              <p className="text-gray-600 text-sm leading-relaxed mb-6">
                {sc.desc}
              </p>
            </div>
            
            <button 
              onClick={() => handleRunSimulation(sc)}
              disabled={running === sc.id}
              className={`w-full py-2.5 rounded-lg flex items-center justify-center font-medium text-sm transition-colors ${
                running === sc.id 
                  ? 'bg-blue-100 text-blue-400 cursor-not-allowed' 
                  : 'bg-blue-600 hover:bg-blue-700 text-white shadow-sm'
              }`}
            >
              <Play size={16} className="mr-2 fill-current" />
              {running === sc.id ? 'Running...' : 'Run Scenario'}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
